# Generated by Django 2.2.10 on 2020-02-07 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driversearch',
            name='capacity_level',
        ),
    ]
