# Generated by Django 2.2.10 on 2020-02-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_auto_20200207_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='share_passenger_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='capacity_level',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('LUX', 'Luxury')], max_length=3, null=True),
        ),
    ]
