# Generated by Django 2.2.10 on 2020-02-06 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('is_driver', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('licence', models.CharField(default='000000000000', max_length=12)),
                ('car_id', models.CharField(default='CDC-000000', max_length=10)),
                ('level', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('LUX', 'Luxuary')], default='S', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
