# Generated by Django 2.2.10 on 2020-02-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_passenger',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='special',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
